-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "blackTimeMs" INTEGER NOT NULL DEFAULT 600000,
ADD COLUMN     "turnStartedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "whiteTimeMs" INTEGER NOT NULL DEFAULT 600000;
